version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/busbooking
      - JWT_SECRET=your_secret_key
      - PORT=5000
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
